[package]
name = "brew-explorer"
version = "0.1.5"
edition = "2024"
authors = [
    "Cosmin Catalin SANDA <me@cosminsanda.com>",
]

[dependencies]
ratatui = "0"
crossterm = "0"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nestify = "0"